# ~/.starship/starship
add_newline = true

# format="""
# [â”Œâ”€â”€â”€ïŒ’ ](green)[â”€â”€â”€ïŠ½ ](blue)$username$hostname$directory$python$conda$rust$node$elm$lua$java$golang$erlang$package$git_branch$git_commit$git_state$git_status$hg_branch$docker_context$cmake$jobs$time
# [â””](green)$character
# """

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"
disabled=true

[[battery.display]]
threshold = 30
style = "bold red"

[[battery.display]]
threshold = 60
style = "bold orange"

[[battery.display]]
threshold = 75
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"

# [character]
# success_symbol = "[ï„¸](green)"  # nf-fa-angle_double_right
# error_symbol = "[ï„·](#ff2a00)"  # nf-fa-ban
# vicmd_symbol = "[ï„·](bold #ffaa00)"  # nf-fa-angle_double_left

[cmd_duration]
style = "8"
show_milliseconds = true
min_time = 30_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = "took [$duration]($style)"

[directory]
truncation_length = 1
style = "yellow"
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = "îœ¥ [$branch]($style) "
style = "yellow"

[git_commit]
commit_hash_length = 8
style = "white"

[git_state]
progress_divider = " of "

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count} "
behind = "ğŸ¢ Ã—${count} "
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count} "
untracked = "ğŸ›¤ï¸  Ã—${count} "
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count} "
staged = "ğŸ—ƒï¸ Ã—${count} "
renamed = "ğŸ“› Ã—${count} "
deleted = "ğŸ—‘ï¸ Ã—${count} "
style = "bright-white "
format = "$all_status$ahead_behind"
disabled = true

[hostname]
ssh_only = false
format = "[$hostname]($style) "
trim_at = ""
style = "bold dimmed #9fe820"
disabled = true

[julia]
format = "[$symbol$version]($style) "
symbol = "à®ƒ "
style = "bold green"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
show_percentage = true
show_swap = true
threshold = 50
style = "bold bright white"
disabled = false

[nodejs]
symbol = "ï¢˜ "
style = "bold #00ff11"
format = "[$symbol$version]($style) "

[package]
disabled = true

[python]
symbol = "îˆµ "
style = "yellow"
format = "[$symbol$version]($style) "
pyenv_version_name = true
disabled = true

[rust]
symbol = "î¨ï¸ " 
style = "bold #fca103"
format = "[$symbol$version]($style) "
disabled = true

[time]
time_format = "%T"
format = "ğŸ•™ $time($style) "
style = "bright-white"
disabled = true

[username]
style_user = "blue"
format = "[$user]($style) "
disabled = true
